# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Delivery

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run sbt assembly
      run: sbt assembly
    - name: Fixing relative paths and copying README.md into docs
      run: |
        sed -i 's|./docs/|./|g' README.md
        cp README.md docs/00_Indice.md
    - uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: docs
        output_dir: pdfs
        images_dir: docs/img
        build_html: false
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SGE.jar
          pdfs/*
