# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Delivery

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"

permissions:
  contents: read

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Set up JDK 21
     # uses: actions/setup-java@v4
      #with:
       # java-version: '21'
       # distribution: 'temurin'
    - name: Run sbt assembly
      run: sbt assembly
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: SGE.jar
        body_path: ${{ github.workspace }}-CHANGELOG.txt

