# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Delivery

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run sbt assembly
      run: sbt assembly
    - name: Fixing relative paths and copying README.md into docs
      run: |
        sed -i 's|./docs/|./|g' README.md
        cp README.md docs/00_Indice.md
    - name: Publish PDF Document
      id: publish-document
      uses: shrink/actions-document-publish@v1
      with:
        sources: 'README.md docs/*.md'
    - name: Rename pdf file
      run: mv ${{ steps.publish-document.outputs.pdf }} "./Documentazione.pdf"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          SGE.jar
          Documentazione.pdf
